# Use PHP 8.0 FPM official image as the base
FROM php:8.0-fpm
  
# Set maintainer label
LABEL maintainer="Taylor Otwell"

# Arguments for user and group creation
ARG WWWUSER=1337
ARG WWWGROUP=1000

# Set working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gosu \
    curl \
    zip \
    unzip \
    git \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    nodejs \
    npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd soap intl

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Install Node.js and Yarn (adjust Node.js setup version as needed)
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs \
    && npm install --global yarn

# Copy existing application directory contents and set permissions
COPY . .
RUN chown -R www-data:www-data /var/www/html \
    && find /var/www/html -type d -exec chmod 755 {} \; \
    && find /var/www/html -type f -exec chmod 644 {} \;

# Copy custom scripts and configurations
COPY start-container /usr/local/bin/start-container
COPY php.ini $PHP_INI_DIR/conf.d/

# Ensure scripts are executable
RUN chmod +x /usr/local/bin/start-container

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Use the custom start script as the entry point
ENTRYPOINT ["start-container"]

#abc
