version: '3'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: 'www-data'
        container_name: laravel
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        environment:
           - DB_CONNECTION=mysql
           - DB_HOST=vaanee-db.c5q46gg0ehzk.ap-south-1.rds.amazonaws.com
           - DB_PORT=3306
           - DB_DATABASE=vaanee_prod
           - DB_USERNAME=admin
           - DB_PASSWORD=GtzORW9X4Y6h9L6alglU
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
